
services:
  music_league_tor1:
    image: dperson/torproxy
    container_name: music_league_tor1
    ports:
      - "9050:9050"

  music_league_tor2:
    image: dperson/torproxy
    container_name: music_league_tor2
    ports:
      - "9052:9050"

  music_league_tor3:
    image: dperson/torproxy
    container_name: music_league_tor3
    ports:
      - "9054:9050"

  music_league_tor4:
    image: dperson/torproxy
    container_name: music_league_tor4
    ports:
      - "9056:9050"

  music_league_tor5:
    image: dperson/torproxy
    container_name: music_league_tor5
    ports:
      - "9058:9050"

  music_league_tor6:
    image: dperson/torproxy
    container_name: music_league_tor6
    ports:
      - "9060:9050"

  music_league_tor7:
    image: dperson/torproxy
    container_name: music_league_tor7
    ports:
      - "9062:9050"

  music_league_tor8:
    image: dperson/torproxy
    container_name: music_league_tor8
    ports:
      - "9064:9050"
